# Generated by Django 5.2.6 on 2025-10-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='requested_help_type',
            field=models.CharField(blank=True, choices=[('acute_validation', 'acute_validation'), ('acute_skills', 'acute_skills'), ('chronic_education', 'chronic_education'), ('chronic_validation', 'chronic_validation'), ('max_validation', 'max_validation'), ('max_assessment', 'max_assessment')], help_text='What kind of support do you need today?', max_length=20, null=True),
        ),
    ]
